### ISSUE TITLE
No `index.html` being generated by sphinx

### ISSUE THREAD

**Issue by tngTUDOR** [brightway-lca/brightway-documentation#103]
As maintainers of the project, readthedocs.org has sent us messages warning us that starting August 1st, there will be trouble if the project doesn't produce an "index.html":

> Hello,
You are receving this email because your Read the Docs project is impacted by an upcoming deprecation.
>
> Historically, Read the Docs has created an auto-generated index.html file with minimal instructions about how to setup the project correctly when your build didn't output this file. This auto-generated file has confused more users than it has helped because the behavior on Read the Docs was different from the behavior on their local environment.
>
> To better onboard users, we have deprecated the auto-creation of index.html files on Read the Docs projects. We will now check for an index.html file at the end of the build, and fail it with a clear message of the problem if there is no index.html file in the top level of your output directory.
>
> Builds from projects that are not generating an index.html file will start to fail on August 1st. Make sure your project is properly configured and it's creating an index.html file before that date to avoid unexpected behaviors.
>
>We are sending you this email because you are a maintainer of the following projects that are affected by this removal:
>
>[brightway-documentation](https://readthedocs.org/projects/brightway-documentation/)
We recommend following our [tutorial](https://docs.readthedocs.io/en/stable/tutorial/) to set up your project correctly.
>
>Keep documenting,
>Read the Docs

**Comment by michaelweinold** [comment]
It seems that our current setup successfully produces an `index.html` file at `brightway-documentation/_build/html/index.html`. Also, the recommended tutorial at:

> We recommend following our [tutorial](https://docs.readthedocs.io/en/stable/tutorial/) to set up your project correctly.

never mentions the `index.html` file, nor how its creation can be affected by any of the relevant configuration files.

I'm closing this, confident that we won't be affected 🤞
