### ISSUE TITLE
Logo Path Broken (#2)

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-documentation#106]
Similar (but with a different root cause) to this issue from 2022:

 - https://github.com/brightway-lca/brightway-documentation/issues/59

the logo is rendered correctly on readthedocs, but not in the local build. How that is possible, I don't know - they use the same `environment.yml` (with pinned versions of the theme and Sphinx).

The local build:

```
WARNING: Path to dark image logo does not exist: logo/BW_all_white_transparent_landscape.svg
build succeeded, 239 warnings.
[W 230626 21:18:29 web:2344] 404 GET /_static/BW_all_black_transparent_landscape.svg (127.0.0.1) 0.43ms
```

<img width="453" alt="Screenshot 2023-06-26 at 21 25 47" src="https://github.com/brightway-lca/brightway-documentation/assets/23102087/28f86179-5dcf-4d87-ad4a-532f3641b9d1">

The current workaround is to place a copy of the logo files into the `_static` directory, not in a subdirectory like `_static/logo`. As soon as this has been fixed by the pydata-sphinx-theme team:

 - [x] https://github.com/pydata/pydata-sphinx-theme/issues/1385
 - [ ] https://github.com/pydata/pydata-sphinx-theme/issues/1328

we can remove the copies.

**Comment by tngTUDOR** [comment]
can't reproduce when building with:
```
sphinx-autobuild source _build/html -a -j auto --open-browser
```
or with 
```
sphinx-build source _build/html -b singlehtml -a
```
either

Are you removing the `_build` folder after a couple of builts?

**Comment by michaelweinold** [comment]
...could have been resolved with my upgrade of Sphinx:

 - https://github.com/brightway-lca/brightway-documentation/issues/92

I'll check again.

**Comment by michaelweinold** [comment]
If you start with:

1. A clean (or missing) `_build` folder
2. _Without_ the logos which I copied to the top level of the `_static` folder (eg.`/brightway-documentation/source/_static/BW_all_black_transparent_landscape.svg`) as a temporary workaround:

> The current workaround is to place a copy of the logo files into the _static directory, not in a subdirectory like _static/logo. As soon as this has been fixed by the pydata-sphinx-theme team:

then the issue persists.

**Comment by alyabolowich** [comment]
Did a fresh git clone and build following the instructions and the logo appears. 

![image](https://github.com/brightway-lca/brightway-documentation/assets/54064746/4a7925f2-c127-4a19-9c1a-174e51937164)

**Comment by michaelweinold** [comment]
Neither of the underlying issues https://github.com/pydata/pydata-sphinx-theme/issues/1385 and https://github.com/pydata/pydata-sphinx-theme/issues/1328 were fixed in the latest release of the `pydata-sphinx-theme`. The current workaround _remains_ to retain a copy of all files in `source/_static/logo` also in `source/_static`. Since I implemented this workaround, you are seeing the logo (as you reported).
