### ISSUE TITLE
Implement Translation/Multi-Language Functionality

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-documentation#119]
At the request of Brightway resident linguist @tngTUDOR work is to commence to add multi-language functionality to the Brightway documentation. 

As luck would have it, I recently came across this PR in the `pydata-sphinx-theme` repo related to a project that uses translations heavily:

> [As you support heavy translation I would be happy to promote it to featured afterward, please 
open an issue if I forget.](https://github.com/pydata/pydata-sphinx-theme/pull/1217#issuecomment-1659581174)

 - https://github.com/pydata/pydata-sphinx-theme/pull/1217
 - https://decentralchain.io

Perhaps we could take some inspiration from their setup.

**Comment by michaelweinold** [comment]
If I might be so bold, @tngTUDOR : What is the real case for this? My main concerns:

 - [ ] The API will be in English in any case. Is this just about translating some of the "explanations" pages (`Introduction`, `LCA`, `FAQ`)?
 - [ ] Browser translation might work better even if we set multi-lang support perfectly, without the need for any overhead on our side.

**Comment by tngTUDOR** [comment]
yes, I was thinking specifically about the "explanations" pages themselves. @michaelweinold can you point me to what you mean by "browser translation" ?

**Comment by michaelweinold** [comment]
> can you point me to what you mean by "browser translation"? 

[Chrome (native)](https://support.google.com/chrome/answer/173424?hl=en&co=GENIE.Platform%3DDesktop)
[Safari (native)](https://support.apple.com/en-gb/guide/safari/ibrw646b2ca2/mac)
[Firefox (plugin)](https://support.mozilla.org/en-US/questions/1074501)

**Comment by michaelweinold** [comment]
...maybe as additional food for thought:

How would we ensure that contributions such as eg. https://github.com/brightway-lca/brightway-documentation/pull/118 are propagated to the other-than-English branches? 

Would we auto-translate those (in which case, 👀 browser translation) or would we need to set up a strategy that assigns language experts (from the Brightway developers?) to these PRs?
