### ISSUE TITLE
'brightway examples' submodule and 'bw2io' directory not found during setup

### ISSUE THREAD

**Issue by PGjedde** [brightway-lca/brightway-documentation#122]
I am trying to setup conda environment to start supporting the brightway documentation as intended by the https://github.com/brightway-lca/brightway-documentation/tree/main.

I run in to some issues, and I am not sure which is the actual issue and why it is happening, or if they're related or two separate issues.
First, when setting up the repository submodules with
`git submodule update --init --recursive --remote --force`
using git bash, it seems to work fine for all submodules except one:

> /brightway-documentation` (main)
     $ git submodule update --init --recursive --remote --force
     **fatal**: No url found for submodule path 'source/content/gallery/brightway-examples' in .gitmodules

From here I just continued anyway with the setup guide. Until eventually in anaconda prompt from my activated sphinx environment I get the following error:

> (sphinx) C:\Users\myuser\brightway-documentation>sphinx-build source _build/html -b singlehtml -a
     **Extension error**:
     AutoAPI Directory `C:\Users\philipgj\Git\brightway-documentation\brightway2-io\bw2io` not found. Please check your 
     `autoapi_dirs` setting.

**Comment by michaelweinold** [comment]
Thank you for reporting this! I’m currently on holiday, but promise to take a look Wednesday next week.

**Comment by michaelweinold** [comment]
Should be resolved with https://github.com/brightway-lca/brightway-documentation/commit/75358de1038e7b962d738f20cd82a09827408c16. Please confirm and close the issue if the build completes without errors.

**Comment by PGjedde** [comment]
Hi Michael, I tested it out and it works - amazing, thank you! I see you already closed the issue so I guess you expected that :)
