### ISSUE TITLE
Minor change to discussion template?

### ISSUE THREAD

**Issue by marc-vdm** [brightway-lca/brightway-documentation#132]
Instead of `value`,  I think you can use `placeholder`, see [documentation here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)

And relevant line in the [discussion template here](https://github.com/brightway-lca/brightway-documentation/blob/0202e428b69045f88b36b47720400216db4c3d91/.github/DISCUSSION_TEMPLATE/documentation-request.yml?plain=1#L29C35-L29C35)

I'm also not 100% sure, but I don't think you need `title`, at leas you don't need it with issue templates.

**Comment by michaelweinold** [comment]
Thank you for the feedback - I dropped `title` from the discussion template in `brightway-live` today (and that worked). So I'm assuming that applies here also.
