### ISSUE TITLE
Search Function returns limited Results

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-documentation#133]
A search for the `bw2data.projects.delete_project()` function returns nothing from the API documentation (where I would expect at least one result). All I get is [a link to a notebook](https://docs.brightway.dev/en/latest/content/examples/brightway-examples/data_import/ecoinvent_import.html) where I use the function.

<img width="581" alt="Screenshot 2023-09-19 at 12 30 14" src="https://github.com/brightway-lca/brightway-documentation/assets/23102087/5e6ccf62-2f78-4628-8c61-d5d03ce1c60f">

**Comment by michaelweinold** [comment]
`delete_project()` is not a method of `bw2data.projects`, but is instead defined in:

[`bw_projects.core.delete_project()`](https://github.com/brightway-lca/bw_projects/blob/00926d6d6c4c10edf2973776f7b7d6e0ba6e6c5f/bw_projects/core.py#L149)

`bw_projects` is currently not captured by the API documentation.

**Comment by tjlca** [comment]
Search Term: **Export project/Share project:**

I do not get much meaningful result although the function that is helpful does show up in the search. [bw2io.backup](https://docs.brightway.dev/en/latest/api/bw2io/backup/index.html?highlight=export%20project)

Can it be made easier to understand that the way to share project between users are these functions? 


Search Term: **Copy database**

The search result shows up quite later on the search page. While advanced users might find this easy, one might get confused as to how to use the copy function? Is it db.copy()? So we need to get the db withing a variable. From the page it seems bw2data.backends.base is the module that contains the copy,write,delete functions. Can some of these important functions be provided a page with examples of their own for easy searching? I can think of copy project, delete project, copy database, delete database. 

Search Term: **copy project**

Did not find any meaningful functions. It seems the search is taking copy and project separately. Tried copy+project and search results were extremely limited. 

Search term: **delete database**

Did not find any meaningful functions immediately. I will probably try db.delete() but not sure if it will work. Trying database+delete helped me get this function. https://docs.brightway.dev/en/latest/api/bw2data/backends/base/index.html#bw2data.backends.base.SQLiteBackend.delete

**Comment by michaelweinold** [comment]
The utility of the search function was greatly improved after adding the "cheat sheet" of @ KarinTreyer in https://github.com/brightway-lca/brightway-documentation/issues/147: 
https://github.com/brightway-lca/brightway-documentation/commit/9b389ff4387d8b0d17446c64821993d23c86f28a
