### ISSUE TITLE
Legacy version of installation page 

### ISSUE THREAD

**Issue by massimopizzol** [brightway-lca/brightway-documentation#137]
This page: https://docs.brightway.dev/en/legacy/content/installation/installation.html  gives a "Page Not Found (404)" error. Is this because installation of bw version 2 is no longer recommended? Then I would at least redirect to a page that informs about this.

**Comment by michaelweinold** [comment]
...no, we just decided to change the name of the _Setup_ page to _Installation_ in the `latest` version of the documentation. I just updated the `legacy` version to reflect this change: https://github.com/brightway-lca/brightway-documentation/commit/6e6537ff6bb05eb5dfbf610dcb89f25e76ec9a58

**Comment by michaelweinold** [comment]
There is an unrelated build issue that needs to be resolved first, but this specific issue is resolved.

**Comment by michaelweinold** [comment]
@massimopizzol, the link now resolves successfully 🎉
