### ISSUE TITLE
`brightway_nosolver` probably no longer needed for Apple MX chips

### ISSUE THREAD

**Issue by romainsacchi** [brightway-lca/brightway-documentation#141]
Running a regular install (`conda install brightway2`) will install all the needed libraries (including `scikit-umfpack`).

**Comment by cmutel** [comment]
Thanks! You are right. However, the documentation you are referring to is for 2.5 :) But the point is still valid, and deeper than just the docs. We need to adapt the Conda recipe. This is actually much easier on Conda than it is [when using pip](https://docs.brightway.dev/en/latest/content/installation/index.html) as we don't need to compile UMFPACK.

**Comment by cmutel** [comment]
Also, there is no package `brightway_nosolver` in any case 👅

**Comment by michaelweinold** [comment]
I am sorry, @cmutel please be more specific:

> We need to adapt the Conda recipe. 

Why is that?

Is the long and elaborate installation procedure for macOS (Apple Silicon) which you added in https://github.com/brightway-lca/brightway-documentation/commit/95a9b2647c6f9216e5059262de7e91f5ad6b0c6c still required?

The whole installation instructions are rather confusing to me at this point - and I have spent _a lot of time_ on the documentation.

**Comment by cmutel** [comment]
> The whole installation instructions are rather confusing to me at this point 

That's not great... I tried to make it a step by step process, but of course what works for me doesn't always work for others.

Is there something specific which you find confusing?

**Comment by michaelweinold** [comment]
Ok, that makes it clear - I had not yet fully internalized the fact that we now have `pip` installation instructions also.
