### ISSUE TITLE
Add a "Definitions"/Terminology Page

### ISSUE THREAD

**Issue by marc-vdm** [brightway-lca/brightway-documentation#146]
Hey docs team!

I have a suggestion/request:
__Problem__
The BW ecosystem has become an important cornerstone of the academic LCA world. However, BW has its own dialect of LCA terms, somewhat separate from ISO/academia. Over the past few years I've had some AB users ask us what certain things mean, as they're used to other terminology. A good paper explaining this problem much more generally would be Ghose et al. [2021](https://onlinelibrary.wiley.com/doi/full/10.1111/jiec.13220).

__Suggestion__
What I'd like to suggest is to add a `definitions` page in the documentation that functions as a dictionary between BW and either this core ontology from Ghose et al. [2021](https://onlinelibrary.wiley.com/doi/full/10.1111/jiec.13220) or the ISO 14044 [2006](https://www.iso.org/standard/38498.html) definitions. It could be a good idea to include such a dictionary as machine readable files in BW as well, but I'll leave that up to you all for discussion.

On the AB side, I'd like to be able to link to such a dictionary so users can always find what BW/AB terms mean in other LCA contexts (Also see https://github.com/LCA-ActivityBrowser/activity-browser/issues/1277 for reference of the original idea)

Let me know what you think about this and whether we should undertake a project like this, I don't think it'd be _that_ much work.

**Comment by michaelweinold** [comment]
This sounds like a fantastic idea! The search function of our Sphinx theme is only as good as the content (obviously) - so a Terminology page would greatly augment the search-ability of the documentation in general.

I would be happy to swiftly merge a PR with a markdown table of the most commonly used LCA terms. Perhaps we can place it at `Home > Theory > Terminology`?

**Comment by marc-vdm** [comment]
Awesome, have a look at https://github.com/LCA-ActivityBrowser/activity-browser/issues/1277 to see if it's useful as a start!
