### ISSUE TITLE
`sphinx-autobuild` won't stop rendering 🙈

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-documentation#154]
...I guess I need to figure out how to properly pass the `api` directory [to either `--re-ignore` or `--ignore`](https://github.com/sphinx-doc/sphinx-autobuild?tab=readme-ov-file#command-line-options).

**Comment by tngTUDOR** [comment]
this has bitten me too, and I haven't found a solution :(

**Comment by michaelweinold** [comment]
We're not the only ones - let's hope someone merges the PRs of the QuantStack folks soon. In the meantime, I opened a discussion here: https://github.com/orgs/sphinx-doc/discussions/12381
