### ISSUE TITLE
Create characterization factor matrix from your own data

### ISSUE THREAD

**Issue by LuisMauricioOG** [brightway-lca/brightway-documentation#156]
I use the Dynamic Probabilistic Material Flow Analysis (https://github.com/empa-tsl/dpmfa) to create a prospective scenario for different nanomaterials released from products. I would like to use the results to determine the nano-specific CF required for performing a LCA (prospective scenarios). However, I am building the databases for the specific cases (with Industry, literature, and experimental results from colleagues). How could I connect DPMFA (including the probabilistic results) with Brightway?

**Comment by michaelweinold** [comment]
@LuisMauricioOG, I added a new section to the Getting Started pages: [Impact Assessment Methods](https://docs.brightway.dev/en/latest/content/gettingstarted/methods.html).

I will try to add an example notebook on creating custom methods later this week.
