### ISSUE TITLE
Peculiar Module/Class Structure causes Build-Breaking Inheritance Diagram Error

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-documentation#162]
...see here:

 - https://github.com/brightway-lca/brightway2-data/issues/186
 - https://github.com/readthedocs/sphinx-autoapi/issues/480

**Comment by michaelweinold** [comment]
The current remedy is to disable the `'show-inheritance-diagram'` option in `autoapi_options` of `conf.py`.

**Comment by cmutel** [comment]
I have looked into this, and there are a lot of libraries which use the current `bw2data.parameters` structure. We definitely can't just add a breaking change. My judgment is that the marginal value of these inheritance diagrams is lower than the effort to change the `bw2data` structure - maybe we leave the "current remedy" for now?

**Comment by michaelweinold** [comment]
Sure, I will add the MWE to reproduce the issue to the issue I opened here: https://github.com/readthedocs/sphinx-autoapi/issues/480. It seems like this could be fixed by the Sphinx extension.
