### ISSUE TITLE
Minor suggestions glossary

### ISSUE THREAD

**Issue by marc-vdm** [brightway-lca/brightway-documentation#170]
The [glossary](https://github.com/brightway-lca/brightway-documentation/edit/main/source/content/other/glossary.md) has some minor problems:

1. Footnote 1 refers to biosphere exchange, that table doesn't exist anymore (I think it'd be better to add the table than to remove the footnote)
2. **Characterization factor** and **Impact Assessment** are discussed before **Demand**  and **LCI**. It may be more logical to move CF and LCIA to after demand, as that better reflects steps taken in an LCA
3. I think in some places **Method** is referred to as 'Impact Category' in Brightway, so this is not entirely consistent -but that's more a Birghtway problem-

**Comment by michaelweinold** [comment]
...we're moving fast and breaking things during the hackathon. Your valuable contribution to the original glossary will not be lost. They are about to be merged with some additional entries of @cmutel.
