### ISSUE TITLE
Typo in Cheatsheet

### ISSUE THREAD

**Issue by CristinaMadrid** [brightway-lca/brightway-documentation#176]
Hi eveyrone,
I promise i will try to learn how to propose changes myself. But for the moment I spotted 
a typo  in this section:
https://docs.brightway.dev/en/latest/content/cheatsheet/importing.html#how-can-i-import-a-local-copy-of-an-ecoinvent-release

In
```
importer = bi.SingleOutputEcospold2Importer(
    dirpath='<ecoinvent_database_zip_file>',
    dbname='<database_name>'
)
importer.apply_strategies()
importer.write_database()
```
dbname should read db_name

**Comment by michaelweinold** [comment]
Thank you for raising this issue. The typo has been fixed.
