### ISSUE TITLE
Logo path broken (#1)

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-documentation#59]
https://github.com/pydata/pydata-sphinx-theme/pull/1132 broke my logo 😭

**Comment by michaelweinold** [comment]
https://github.com/brightway-lca/brightway-documentation/commit/1f1aaec68375fc3fce2c08f37d2b146852ec075f fixed it.

**Comment by michaelweinold** [comment]
The issue is back (with a vengance?). The logo is rendered correctly on readthedocs, but not in the local build. How that is possible, I don't know - they use the same `environment.yml` (with pinned versions of the theme and Sphinx).

The local build:

```
WARNING: Path to dark image logo does not exist: logo/BW_all_white_transparent_landscape.svg
build succeeded, 239 warnings.
[W 230626 21:18:29 web:2344] 404 GET /_static/BW_all_black_transparent_landscape.svg (127.0.0.1) 0.43ms
```

<img width="453" alt="Screenshot 2023-06-26 at 21 25 47" src="https://github.com/brightway-lca/brightway-documentation/assets/23102087/28f86179-5dcf-4d87-ad4a-532f3641b9d1">

At least I don't think I'm the only one this is affecting:

 - [ ] https://github.com/pydata/pydata-sphinx-theme/issues/1328

**Comment by tngTUDOR** [comment]
+1 here
________________________________

**Comment by michaelweinold** [comment]
![arnie-arnold-schwarzenegger](https://github.com/brightway-lca/brightway-documentation/assets/23102087/d29b8277-b582-4c16-af93-0bc757abc971)

I pinned all package versions AND switched to an `environment.yml` file for both the local and the remote (readthedocs) build _specifically_ to avoid this - HOW is this happening? So annoying!

**Comment by michaelweinold** [comment]
The current workaround is to place a copy of the logo files into the `_static` directory, not in a subdirectory like `_static/logo`. As soon as this has been fixed by the pydata-sphinx-theme team:

 - [ ] https://github.com/pydata/pydata-sphinx-theme/issues/1385

We can remove the copies.
