### ISSUE TITLE
Add documentation/repos on docker images

### ISSUE THREAD

**Issue by tngTUDOR** [brightway-lca/brightway-documentation#65]
The latest docker images built by brightway-lca deserve a place in the documentation.

**Comment by michaelweinold** [comment]
I suggest a sub-page of the [Setup](https://documentation.brightway.dev/en/latest/source/setup/setup.html) page.

**Comment by michaelweinold** [comment]
@tngTUDOR gimme gimme gimme the docs for the docker 🎶🎉

**Comment by tngTUDOR** [comment]
issue-65 branch will include fix for this

**Comment by tngTUDOR** [comment]
There will only be "documentation" added, not the full repo(s) of the docker images for the moment.

**Comment by tngTUDOR** [comment]
@michaelweinold  please wait to merge until I figure out if we a "autobuild" API like documentation for the docker images is useful / necessary

**Comment by michaelweinold** [comment]
Sure, I'll wait for your go-ahead. Please just check with me first if you end up deciding you want to autobuild ([we are currently using `sphinx-autobuild=2021.3.14`](https://github.com/brightway-lca/brightway-documentation/blob/773ce2632424a5c4aa77ab248b3845547cfda0f4/environment.yml#L14)) as you likely already know.

**Comment by tngTUDOR** [comment]
You can go ahead with the merge @michaelweinold
