### ISSUE TITLE
Add Footer with "open an issue on GitHub" or similar

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-documentation#73]
To make the possibility of:

1. contributing to the documentation
2. complaining about errors/mistakes in the documentation
3. asking for elaboration/clarification in the documentation

more visible, a footer should be added.

Compare also:

 - [ ] `pydata-sphinx-theme`: [`"footer_items"`](https://github.com/pydata/pydata-sphinx-theme/blob/d98350b581b5dd804b918b1f6c82a51964957df8/docs/conf.py#L163)
 - [ ] https://github.com/pydata/pydata-sphinx-theme/pull/1184#issuecomment-1497220402
 - [x] https://github.com/pydata/pydata-sphinx-theme/issues/1284

**Comment by michaelweinold** [comment]
...it seems [Bokeh](https://docs.bokeh.org/en/latest/) is using a custom footer.

**Comment by 12rambau** [comment]
I'm -1 to add this component in the built-in widgets. The github link can be added in the header and there is everything to create highly customized widgets in templates. what about others ?
