### ISSUE TITLE
Add "Edit on GitHub" and "Support" Buttons

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-documentation#80]
...like implemented in [the ArviZ documentation](https://python.arviz.org/en/stable/getting_started/index.html):

<img width="248" alt="Screenshot 2023-04-16 at 09 11 45" src="https://user-images.githubusercontent.com/23102087/232325432-48478880-e87e-4f9b-90f0-400513d35fbb.png">

Relevant theme option: [`secondary-sidebar-right`](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/layout.html#secondary-sidebar-right)

**Comment by michaelweinold** [comment]
- [ ] @cmutel, please provide a hyperlink (to the relevant Cauldron website, or potentially to [Tidelift](https://tidelift.com/)?) for the `Support Brightway` button.

**Comment by cmutel** [comment]
I think that support should be a separate page/section, with multiple options.

The most important thing people can do now is to help with the documentation; this should be clearly communicated.

We can also offer the option to get commercial support from Cauldron; but we can also let others throw their hat in the ring; @Loisel, @BenPortner please chime in here if you want.

We can also offer DdS memberships or financial donations, though we should be clear this goes more towards organizing Brightway events and Brightway teaching.

**Comment by michaelweinold** [comment]
Ok, I'll add a `Support` page that is linked through the button.
