### ISSUE TITLE
document the use of "singlehtml"

### ISSUE THREAD

**Issue by tngTUDOR** [brightway-lca/brightway-documentation#97]
## Current

following the instructions in the readme to build a "single html" fails: links to other parts of the documentation are only "#"

## Expected

README instructions to build your own version of the documentation for testing should include the exact reproducible steps.

My current working flow to test is: (using sphinx 5)

- mamba env create --file environment.yml
- mamba activate sphinx
- sphinx-build source build/html -a

then

- cd _build/html/content
-  python -m http.server

**Comment by michaelweinold** [comment]
...fixed. Both local build instructions (autobuild/manual) now working.
